### ISSUE TITLE
iterative ref: MASTER ISSUE: Implement expectation maximization iterative refinement

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/reconstructSPI#29]
Master issue of

- [ ] https://github.com/compSPI/reconstructSPI/issues/53
- [x] https://github.com/compSPI/reconstructSPI/issues/52
- [ ] https://github.com/compSPI/reconstructSPI/issues/50
- [ ] https://github.com/compSPI/reconstructSPI/issues/42
- [ ] https://github.com/compSPI/reconstructSPI/issues/39
- [ ] https://github.com/compSPI/reconstructSPI/issues/37
- [x] https://github.com/compSPI/reconstructSPI/issues/35
- [x] https://github.com/compSPI/reconstructSPI/issues/32
- [ ] https://github.com/compSPI/reconstructSPI/issues/31
- [ ] https://github.com/compSPI/reconstructSPI/issues/30
- [ ] https://github.com/compSPI/reconstructSPI/issues/25
- [x] https://github.com/compSPI/reconstructSPI/issues/24
- [x] https://github.com/compSPI/reconstructSPI/issues/20
- [x] https://github.com/compSPI/reconstructSPI/issues/19
- [x] https://github.com/compSPI/reconstructSPI/issues/18
- [ ] https://github.com/compSPI/reconstructSPI/issues/17
- [x] https://github.com/compSPI/reconstructSPI/issues/16
- [x] https://github.com/compSPI/reconstructSPI/issues/15
- [x] https://github.com/compSPI/reconstructSPI/issues/14
- [x] https://github.com/compSPI/reconstructSPI/issues/13
- [x] https://github.com/compSPI/reconstructSPI/issues/11
- [ ] https://github.com/compSPI/reconstructSPI/issues/10 
- [ ] https://github.com/compSPI/reconstructSPI/issues/6
- [ ] https://github.com/compSPI/reconstructSPI/issues/5
- [ ] https://github.com/compSPI/reconstructSPI/issues/3

Tasks live in project [Implement expectation maximization iterative refinement](https://github.com/orgs/compSPI/projects/2), one github issue per task.

**Comment by geoffwoollard** [comment]
I suggest developing with n_pix=32 or 64 to start with. real data will be more like 128 or 256. Can have issues with ctf at small pixels and need to zero pad to avoid artefacts. The artefacts from the ctf can arise from it not going to zero at edges, and the sinusoidal ctf rippling too fast. 

See Penczek, P. A., Fang, J., Li, X., Cheng, Y., Loerke, J., & Spahn, C. M. T. (2014). CTER-Rapid estimation of CTF parameters with error assessment. Ultramicroscopy, 140, 9–19. http://doi.org/10.1016/j.ultramic.2014.01.009

One can 
* zero pad the real space inputs 
* take the fft on the zero padded inputs
* make the ctf arrays on the lager sized array
